let g:norm_home_dir = substitute(expand('~'), '\', '/', 'g')
let curscrpath = expand('<sfile>:p:h')
execute 'source '. curscrpath . '/basic.vim'
execute 'source '. curscrpath . '/plugins.vim'
execute 'source '. curscrpath . '/misc.vim'
